version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - mynet

networks:
    mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.199.0/24
                  gateway: "10.0.199.1"
